spring.application.name=order-service

# abbitMQ / CloudAMQP
spring.rabbitmq.host=jaragua-01.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=bjnuffmq
spring.rabbitmq.password=gj-YQIiEXyfxQxjsZtiYDKeXIT8ppUq7
spring.rabbitmq.virtual-host=bjnuffmq

# Configura��es do Listener
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Sufixo das filas
app.rabbitmq.custom-suffix=cintia